// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: reminderservice/v1/reminderservice.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PillId       int32  `protobuf:"varint,3,opt,name=pill_id,json=pillId,proto3" json:"pill_id,omitempty"`
	ReminderTime string `protobuf:"bytes,4,opt,name=reminder_time,json=reminderTime,proto3" json:"reminder_time,omitempty"`
	Frequency    string `protobuf:"bytes,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	DaysOfWeek   string `protobuf:"bytes,6,opt,name=days_of_week,json=daysOfWeek,proto3" json:"days_of_week,omitempty"`
	StartDate    string `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate      string `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
}

func (x *AddPlanRequest) Reset() {
	*x = AddPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlanRequest) ProtoMessage() {}

func (x *AddPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlanRequest.ProtoReflect.Descriptor instead.
func (*AddPlanRequest) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{0}
}

func (x *AddPlanRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddPlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddPlanRequest) GetPillId() int32 {
	if x != nil {
		return x.PillId
	}
	return 0
}

func (x *AddPlanRequest) GetReminderTime() string {
	if x != nil {
		return x.ReminderTime
	}
	return ""
}

func (x *AddPlanRequest) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *AddPlanRequest) GetDaysOfWeek() string {
	if x != nil {
		return x.DaysOfWeek
	}
	return ""
}

func (x *AddPlanRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AddPlanRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type AddPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddPlanResponse) Reset() {
	*x = AddPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlanResponse) ProtoMessage() {}

func (x *AddPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlanResponse.ProtoReflect.Descriptor instead.
func (*AddPlanResponse) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{1}
}

type GetUserPlansRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserPlansRequest) Reset() {
	*x = GetUserPlansRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlansRequest) ProtoMessage() {}

func (x *GetUserPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlansRequest.ProtoReflect.Descriptor instead.
func (*GetUserPlansRequest) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPlansRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserPlansResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserPlans []*UserPlan `protobuf:"bytes,1,rep,name=user_plans,json=userPlans,proto3" json:"user_plans,omitempty"`
}

func (x *GetUserPlansResponse) Reset() {
	*x = GetUserPlansResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlansResponse) ProtoMessage() {}

func (x *GetUserPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlansResponse.ProtoReflect.Descriptor instead.
func (*GetUserPlansResponse) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPlansResponse) GetUserPlans() []*UserPlan {
	if x != nil {
		return x.UserPlans
	}
	return nil
}

type UserPlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId       int32  `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PillId       int32  `protobuf:"varint,3,opt,name=pill_id,json=pillId,proto3" json:"pill_id,omitempty"`
	ReminderTime string `protobuf:"bytes,4,opt,name=reminder_time,json=reminderTime,proto3" json:"reminder_time,omitempty"`
	Frequency    string `protobuf:"bytes,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	DaysOfWeek   string `protobuf:"bytes,6,opt,name=days_of_week,json=daysOfWeek,proto3" json:"days_of_week,omitempty"`
	StartDate    string `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate      string `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
}

func (x *UserPlan) Reset() {
	*x = UserPlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPlan) ProtoMessage() {}

func (x *UserPlan) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPlan.ProtoReflect.Descriptor instead.
func (*UserPlan) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{4}
}

func (x *UserPlan) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *UserPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserPlan) GetPillId() int32 {
	if x != nil {
		return x.PillId
	}
	return 0
}

func (x *UserPlan) GetReminderTime() string {
	if x != nil {
		return x.ReminderTime
	}
	return ""
}

func (x *UserPlan) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *UserPlan) GetDaysOfWeek() string {
	if x != nil {
		return x.DaysOfWeek
	}
	return ""
}

func (x *UserPlan) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UserPlan) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type DeleteUserPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId int32 `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
}

func (x *DeleteUserPlanRequest) Reset() {
	*x = DeleteUserPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserPlanRequest) ProtoMessage() {}

func (x *DeleteUserPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserPlanRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserPlanRequest) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserPlanRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type DeleteUserPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUserPlanResponse) Reset() {
	*x = DeleteUserPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserPlanResponse) ProtoMessage() {}

func (x *DeleteUserPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserPlanResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserPlanResponse) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{6}
}

type IntakeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId    int32 `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PillTaken bool  `protobuf:"varint,2,opt,name=pill_taken,json=pillTaken,proto3" json:"pill_taken,omitempty"`
}

func (x *IntakeRequest) Reset() {
	*x = IntakeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntakeRequest) ProtoMessage() {}

func (x *IntakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntakeRequest.ProtoReflect.Descriptor instead.
func (*IntakeRequest) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{7}
}

func (x *IntakeRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *IntakeRequest) GetPillTaken() bool {
	if x != nil {
		return x.PillTaken
	}
	return false
}

type IntakeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IntakeResponse) Reset() {
	*x = IntakeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntakeResponse) ProtoMessage() {}

func (x *IntakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntakeResponse.ProtoReflect.Descriptor instead.
func (*IntakeResponse) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{8}
}

type CancelPlanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId int32 `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
}

func (x *CancelPlanRequest) Reset() {
	*x = CancelPlanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPlanRequest) ProtoMessage() {}

func (x *CancelPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPlanRequest.ProtoReflect.Descriptor instead.
func (*CancelPlanRequest) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{9}
}

func (x *CancelPlanRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type CancelPlanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelPlanResponse) Reset() {
	*x = CancelPlanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPlanResponse) ProtoMessage() {}

func (x *CancelPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reminderservice_v1_reminderservice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPlanResponse.ProtoReflect.Descriptor instead.
func (*CancelPlanResponse) Descriptor() ([]byte, []int) {
	return file_reminderservice_v1_reminderservice_proto_rawDescGZIP(), []int{10}
}

var File_reminderservice_v1_reminderservice_proto protoreflect.FileDescriptor

var file_reminderservice_v1_reminderservice_proto_rawDesc = []byte{
	0x0a, 0x28, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x72, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0xf5,
	0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x70, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x20, 0x0a, 0x0c, 0x64, 0x61,
	0x79, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x61, 0x79, 0x73, 0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x6c, 0x61, 0x6e, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x22, 0xef,
	0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x69, 0x6c, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x69, 0x6c, 0x6c, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x20, 0x0a, 0x0c, 0x64, 0x61, 0x79, 0x73, 0x5f, 0x6f, 0x66, 0x5f,
	0x77, 0x65, 0x65, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x79, 0x73,
	0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65,
	0x22, 0x30, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e,
	0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x0d,
	0x49, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x69, 0x6c, 0x6c, 0x5f, 0x74,
	0x61, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x69, 0x6c, 0x6c,
	0x54, 0x61, 0x6b, 0x65, 0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x49, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70,
	0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50,
	0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xdf, 0x03, 0x0a, 0x0f,
	0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x52, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x22, 0x2e, 0x72, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c,
	0x61, 0x6e, 0x73, 0x12, 0x27, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x72,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x29, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5b, 0x0a, 0x0a, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x25, 0x2e,
	0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x06,
	0x49, 0x6e, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x21, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x61,
	0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x72, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x6e, 0x74, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a,
	0x32, 0x70, 0x69, 0x6c, 0x6c, 0x73, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x72,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reminderservice_v1_reminderservice_proto_rawDescOnce sync.Once
	file_reminderservice_v1_reminderservice_proto_rawDescData = file_reminderservice_v1_reminderservice_proto_rawDesc
)

func file_reminderservice_v1_reminderservice_proto_rawDescGZIP() []byte {
	file_reminderservice_v1_reminderservice_proto_rawDescOnce.Do(func() {
		file_reminderservice_v1_reminderservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_reminderservice_v1_reminderservice_proto_rawDescData)
	})
	return file_reminderservice_v1_reminderservice_proto_rawDescData
}

var file_reminderservice_v1_reminderservice_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_reminderservice_v1_reminderservice_proto_goTypes = []interface{}{
	(*AddPlanRequest)(nil),         // 0: reminderservice.v1.AddPlanRequest
	(*AddPlanResponse)(nil),        // 1: reminderservice.v1.AddPlanResponse
	(*GetUserPlansRequest)(nil),    // 2: reminderservice.v1.GetUserPlansRequest
	(*GetUserPlansResponse)(nil),   // 3: reminderservice.v1.GetUserPlansResponse
	(*UserPlan)(nil),               // 4: reminderservice.v1.UserPlan
	(*DeleteUserPlanRequest)(nil),  // 5: reminderservice.v1.DeleteUserPlanRequest
	(*DeleteUserPlanResponse)(nil), // 6: reminderservice.v1.DeleteUserPlanResponse
	(*IntakeRequest)(nil),          // 7: reminderservice.v1.IntakeRequest
	(*IntakeResponse)(nil),         // 8: reminderservice.v1.IntakeResponse
	(*CancelPlanRequest)(nil),      // 9: reminderservice.v1.CancelPlanRequest
	(*CancelPlanResponse)(nil),     // 10: reminderservice.v1.CancelPlanResponse
}
var file_reminderservice_v1_reminderservice_proto_depIdxs = []int32{
	4,  // 0: reminderservice.v1.GetUserPlansResponse.user_plans:type_name -> reminderservice.v1.UserPlan
	0,  // 1: reminderservice.v1.ReminderService.AddPlan:input_type -> reminderservice.v1.AddPlanRequest
	2,  // 2: reminderservice.v1.ReminderService.GetUserPlans:input_type -> reminderservice.v1.GetUserPlansRequest
	5,  // 3: reminderservice.v1.ReminderService.DeleteUserPlan:input_type -> reminderservice.v1.DeleteUserPlanRequest
	9,  // 4: reminderservice.v1.ReminderService.CancelPlan:input_type -> reminderservice.v1.CancelPlanRequest
	7,  // 5: reminderservice.v1.ReminderService.Intake:input_type -> reminderservice.v1.IntakeRequest
	1,  // 6: reminderservice.v1.ReminderService.AddPlan:output_type -> reminderservice.v1.AddPlanResponse
	3,  // 7: reminderservice.v1.ReminderService.GetUserPlans:output_type -> reminderservice.v1.GetUserPlansResponse
	6,  // 8: reminderservice.v1.ReminderService.DeleteUserPlan:output_type -> reminderservice.v1.DeleteUserPlanResponse
	10, // 9: reminderservice.v1.ReminderService.CancelPlan:output_type -> reminderservice.v1.CancelPlanResponse
	8,  // 10: reminderservice.v1.ReminderService.Intake:output_type -> reminderservice.v1.IntakeResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_reminderservice_v1_reminderservice_proto_init() }
func file_reminderservice_v1_reminderservice_proto_init() {
	if File_reminderservice_v1_reminderservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reminderservice_v1_reminderservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminderservice_v1_reminderservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminderservice_v1_reminderservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPlansRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminderservice_v1_reminderservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPlansResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminderservice_v1_reminderservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminderservice_v1_reminderservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminderservice_v1_reminderservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminderservice_v1_reminderservice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntakeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminderservice_v1_reminderservice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntakeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminderservice_v1_reminderservice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelPlanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reminderservice_v1_reminderservice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelPlanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reminderservice_v1_reminderservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reminderservice_v1_reminderservice_proto_goTypes,
		DependencyIndexes: file_reminderservice_v1_reminderservice_proto_depIdxs,
		MessageInfos:      file_reminderservice_v1_reminderservice_proto_msgTypes,
	}.Build()
	File_reminderservice_v1_reminderservice_proto = out.File
	file_reminderservice_v1_reminderservice_proto_rawDesc = nil
	file_reminderservice_v1_reminderservice_proto_goTypes = nil
	file_reminderservice_v1_reminderservice_proto_depIdxs = nil
}
