// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: pillsservice/v1/pillsservice.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchPillsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchString string `protobuf:"bytes,1,opt,name=search_string,json=searchString,proto3" json:"search_string,omitempty"`
}

func (x *SearchPillsRequest) Reset() {
	*x = SearchPillsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pillsservice_v1_pillsservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPillsRequest) ProtoMessage() {}

func (x *SearchPillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pillsservice_v1_pillsservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPillsRequest.ProtoReflect.Descriptor instead.
func (*SearchPillsRequest) Descriptor() ([]byte, []int) {
	return file_pillsservice_v1_pillsservice_proto_rawDescGZIP(), []int{0}
}

func (x *SearchPillsRequest) GetSearchString() string {
	if x != nil {
		return x.SearchString
	}
	return ""
}

type SearchPillsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pills []*Pill `protobuf:"bytes,1,rep,name=pills,proto3" json:"pills,omitempty"`
}

func (x *SearchPillsResponse) Reset() {
	*x = SearchPillsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pillsservice_v1_pillsservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPillsResponse) ProtoMessage() {}

func (x *SearchPillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pillsservice_v1_pillsservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPillsResponse.ProtoReflect.Descriptor instead.
func (*SearchPillsResponse) Descriptor() ([]byte, []int) {
	return file_pillsservice_v1_pillsservice_proto_rawDescGZIP(), []int{1}
}

func (x *SearchPillsResponse) GetPills() []*Pill {
	if x != nil {
		return x.Pills
	}
	return nil
}

type GetPillByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPillByIdRequest) Reset() {
	*x = GetPillByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pillsservice_v1_pillsservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPillByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPillByIdRequest) ProtoMessage() {}

func (x *GetPillByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pillsservice_v1_pillsservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPillByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPillByIdRequest) Descriptor() ([]byte, []int) {
	return file_pillsservice_v1_pillsservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetPillByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPillByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pill *Pill `protobuf:"bytes,1,opt,name=pill,proto3" json:"pill,omitempty"`
}

func (x *GetPillByIdResponse) Reset() {
	*x = GetPillByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pillsservice_v1_pillsservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPillByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPillByIdResponse) ProtoMessage() {}

func (x *GetPillByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pillsservice_v1_pillsservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPillByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPillByIdResponse) Descriptor() ([]byte, []int) {
	return file_pillsservice_v1_pillsservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetPillByIdResponse) GetPill() *Pill {
	if x != nil {
		return x.Pill
	}
	return nil
}

type Pill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Dosage      string `protobuf:"bytes,3,opt,name=dosage,proto3" json:"dosage,omitempty"`
	Instruction string `protobuf:"bytes,4,opt,name=instruction,proto3" json:"instruction,omitempty"`
}

func (x *Pill) Reset() {
	*x = Pill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pillsservice_v1_pillsservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pill) ProtoMessage() {}

func (x *Pill) ProtoReflect() protoreflect.Message {
	mi := &file_pillsservice_v1_pillsservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pill.ProtoReflect.Descriptor instead.
func (*Pill) Descriptor() ([]byte, []int) {
	return file_pillsservice_v1_pillsservice_proto_rawDescGZIP(), []int{4}
}

func (x *Pill) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pill) GetDosage() string {
	if x != nil {
		return x.Dosage
	}
	return ""
}

func (x *Pill) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

var File_pillsservice_v1_pillsservice_proto protoreflect.FileDescriptor

var file_pillsservice_v1_pillsservice_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x69, 0x6c, 0x6c, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x69, 0x6c, 0x6c, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x69, 0x6c, 0x6c, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x39, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50,
	0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x22, 0x42, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x69, 0x6c, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x69, 0x6c, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x69, 0x6c, 0x6c, 0x73, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6c, 0x6c, 0x52, 0x05, 0x70,
	0x69, 0x6c, 0x6c, 0x73, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x69, 0x6c, 0x6c, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x50, 0x69, 0x6c, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x29, 0x0a, 0x04, 0x70, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x69, 0x6c, 0x6c, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x70, 0x69, 0x6c, 0x6c, 0x22, 0x64, 0x0a, 0x04,
	0x50, 0x69, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x32, 0xc2, 0x01, 0x0a, 0x0c, 0x50, 0x69, 0x6c, 0x6c, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x69, 0x6c,
	0x6c, 0x73, 0x12, 0x23, 0x2e, 0x70, 0x69, 0x6c, 0x6c, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x69, 0x6c, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x69, 0x6c, 0x6c, 0x73, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x50, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x50, 0x69, 0x6c, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x12, 0x23, 0x2e, 0x70,
	0x69, 0x6c, 0x6c, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x69, 0x6c, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x70, 0x69, 0x6c, 0x6c, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x69, 0x6c, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x70, 0x69, 0x6c, 0x6c, 0x73,
	0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x69, 0x6c, 0x6c, 0x73, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pillsservice_v1_pillsservice_proto_rawDescOnce sync.Once
	file_pillsservice_v1_pillsservice_proto_rawDescData = file_pillsservice_v1_pillsservice_proto_rawDesc
)

func file_pillsservice_v1_pillsservice_proto_rawDescGZIP() []byte {
	file_pillsservice_v1_pillsservice_proto_rawDescOnce.Do(func() {
		file_pillsservice_v1_pillsservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_pillsservice_v1_pillsservice_proto_rawDescData)
	})
	return file_pillsservice_v1_pillsservice_proto_rawDescData
}

var file_pillsservice_v1_pillsservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pillsservice_v1_pillsservice_proto_goTypes = []interface{}{
	(*SearchPillsRequest)(nil),  // 0: pillsservice.v1.SearchPillsRequest
	(*SearchPillsResponse)(nil), // 1: pillsservice.v1.SearchPillsResponse
	(*GetPillByIdRequest)(nil),  // 2: pillsservice.v1.GetPillByIdRequest
	(*GetPillByIdResponse)(nil), // 3: pillsservice.v1.GetPillByIdResponse
	(*Pill)(nil),                // 4: pillsservice.v1.Pill
}
var file_pillsservice_v1_pillsservice_proto_depIdxs = []int32{
	4, // 0: pillsservice.v1.SearchPillsResponse.pills:type_name -> pillsservice.v1.Pill
	4, // 1: pillsservice.v1.GetPillByIdResponse.pill:type_name -> pillsservice.v1.Pill
	0, // 2: pillsservice.v1.PillsService.SearchPills:input_type -> pillsservice.v1.SearchPillsRequest
	2, // 3: pillsservice.v1.PillsService.GetPillById:input_type -> pillsservice.v1.GetPillByIdRequest
	1, // 4: pillsservice.v1.PillsService.SearchPills:output_type -> pillsservice.v1.SearchPillsResponse
	3, // 5: pillsservice.v1.PillsService.GetPillById:output_type -> pillsservice.v1.GetPillByIdResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pillsservice_v1_pillsservice_proto_init() }
func file_pillsservice_v1_pillsservice_proto_init() {
	if File_pillsservice_v1_pillsservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pillsservice_v1_pillsservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPillsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pillsservice_v1_pillsservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPillsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pillsservice_v1_pillsservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPillByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pillsservice_v1_pillsservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPillByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pillsservice_v1_pillsservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pillsservice_v1_pillsservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pillsservice_v1_pillsservice_proto_goTypes,
		DependencyIndexes: file_pillsservice_v1_pillsservice_proto_depIdxs,
		MessageInfos:      file_pillsservice_v1_pillsservice_proto_msgTypes,
	}.Build()
	File_pillsservice_v1_pillsservice_proto = out.File
	file_pillsservice_v1_pillsservice_proto_rawDesc = nil
	file_pillsservice_v1_pillsservice_proto_goTypes = nil
	file_pillsservice_v1_pillsservice_proto_depIdxs = nil
}
