version: "3"

services:
  mobileapi:
    ports:
      - 5000:5500
      - 8001:8000
    image: reminder_mobileapi:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
    environment:
      SERVER_PORT: 5500
      GRPC_SERVER_PORT: 8000
      DB_POSTGRES_HOST: database
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USERNAME: postgres
      DB_POSTGRES_PASSWORD: developer2023!$$4 # one $ is escaped by $$, real password is developer2023!$4
      DB_POSTGRES_DBNAME: postgres
      EXTERNALSERVICES_PILLSSERVICE_ADDRESS: pillsservice:8000
      EXTERNALSERVICES_REMINDERSERVICE_ADDRESS: reminderservice:8000
    depends_on:
      - database

  pillsservice:
    ports:
      - 8002:8000
    image: reminder_pillsservice:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
    environment:
      GRPC_SERVER_PORT: 8000
      DB_POSTGRES_HOST: database
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USERNAME: postgres
      DB_POSTGRES_PASSWORD: developer2023!$$4 # one $ is escaped by $$, real password is developer2023!$4
      DB_POSTGRES_DBNAME: postgres
    depends_on:
      - database

  reminderservice:
    ports:
      - 8003:8000
    image: reminder_reminderservice:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
    environment:
      GRPC_SERVER_PORT: 8000
      DB_POSTGRES_HOST: database
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USERNAME: postgres
      DB_POSTGRES_PASSWORD: developer2023!$$4 # one $ is escaped by $$, real password is developer2023!$4
      DB_POSTGRES_DBNAME: postgres
      EXTERNALSERVICES_MOBILEAPI_ADDRESS: mobileapi:8000
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: developer2023!$$4 # one $ is escaped by $$, real password is developer2023!$4
      POSTGRES_DB: postgres
    volumes:
      - ./db/dbdata:/var/lib/postgresql/data"