grpc:
  server:
    port: "5003"

  mode: "release"
  logging:
    level: 0
    format: "json"

db:
  postgres:
    dbname: "postgres"
    username: "postgres"
    password: "developer2023!$4"
    host: "localhost"
    port: "5432"
    max_lifetime: 7200
    max_open_conns: 150
    max_idle_conns: 50

externalservices:
  mobileapi:
    address: "localhost:5001"
    timeout: 3s